version: '3.8'

services:
  # Frontend - Next.js AI Research Assistant
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env  # Use your existing .env file
    environment:
      - NEXT_PUBLIC_LANGGRAPH_API_URL=http://langgraph:2024  # Override for Docker networking
      - NEXT_PUBLIC_ASSISTANT_ID=Deep Researcher
    depends_on:
      - langgraph
    networks:
      - ai-research-network

  # LangGraph Backend (assuming you have a Dockerfile for it)
  langgraph:
    build:
      context: .
      dockerfile: Dockerfile  # Your existing LangGraph Dockerfile
    ports:
      - "2024:2024"
    env_file:
      - .env  # Use your existing .env file with all API keys
    volumes:
      - ./src:/app/src
    networks:
      - ai-research-network

networks:
  ai-research-network:
    driver: bridge 