[build]
builder = "nixpacks"

[deploy]
startCommand = "cd frontend && npm start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[build.nixpacks]
workingDirectory = "frontend" 