[build]
builder = "nixpacks"

[deploy]
startCommand = "cd frontend && PORT=8080 HOSTNAME=0.0.0.0 npm start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[variables]
PORT = "8080"
HOSTNAME = "0.0.0.0" 