[build]
builder = "nixpacks"

[deploy]
startCommand = "node frontend/.next/standalone/server.js"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[variables]
PORT = "3000" 