[build]
builder = "nixpacks"

[build.nixpacks]
workingDirectory = "frontend"

[build.nixpacks.config]
buildCommand = "npm ci && npm run build"

[deploy]
startCommand = "node server.js"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[build.nixpacks.env]
NIXPACKS_BUILD_CMD = "npm ci && npm run build" 