[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.backend"

[deploy]
startCommand = "langgraph up --host 0.0.0.0 --port $PORT"
healthcheckPath = "/docs"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[env]
PYTHONPATH = "/app"
LANGCHAIN_API_KEY = "${LANGCHAIN_API_KEY}"
OPENAI_API_KEY = "${OPENAI_API_KEY}"
TAVILY_API_KEY = "${TAVILY_API_KEY}"
SUPABASE_URL = "${SUPABASE_URL}"
SUPABASE_KEY = "${SUPABASE_KEY}" 