[build]
builder = "nixpacks"

[deploy]
startCommand = "node start-server.js"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[variables]
PORT = "8080"
HOSTNAME = "0.0.0.0" 