[build]
builder = "nixpacks"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[build.nixpacks]
workingDirectory = "frontend"

[build.nixpacks.phases.setup]
nixPkgs = ["nodejs_18", "npm-9_x"]

[build.nixpacks.phases.install]
cmds = ["npm ci"]

[build.nixpacks.phases.build]
cmds = ["npm run build"] 